app:
  timezone: Asia/Tokyo

schedule:
  notify_at: "08:00"

email:
  address: "your-address@icloud.com"

x:
  account_name: ""
  api:
    client_id: ""
    callback_url: "http://127.0.0.1:8787/callback"
